
project_id = "hllfwbijqwvxsnishruo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.admin-auth]
verify_jwt = false

[functions.admin-products]
verify_jwt = false
