// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hllfwbijqwvxsnishruo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbGZ3YmlqcXd2eHNuaXNocnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzU5MTEsImV4cCI6MjA2NDY1MTkxMX0.UahnIGZtmvthDyPkboN6ajkTbxWCDazqxs20cx-8CUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);